const DWTool = require("../utils/DWTool")

cc.Class({
    extends: cc.Component,

    properties: {
        itemSprite: [cc.SpriteFrame],
        infoText: cc.RichText,
        statusText: cc.RichText
    },

    /**
     * 初始化一条消息
     * @param {Number} type 消息类型 {1: 可点击, 0: 不可点击}
     * @param {Number} gender 性别 {1: 男, 0: 女}
     */
    // init (type = 0, gender = 0) {
    //     this.node.getComponent(cc.Sprite).spriteFrame = this.itemSprite[type]
    //     let _infoText
    //     if(gender == 1) {
    //         _infoText = `<color=#0eb7db>彭于晏</c>正在挖你的艺人，<br/>Ta正在考虑要不要跳槽`
    //     } else {
    //         _infoText = `<color=#fd7979>许婷</c>挖走了你的艺人，<br/>Ta正在考虑要不要跳槽`
    //     }
    //     this.infoText.string = _infoText;
        
    // },

    /**
     * 初始化一条消息
     * @param {Number} type 消息类型 {1: 可点击, 0: 不可点击}
     * @param {String} msg 消息内容
     * @param {Number} createTime 消息创建时间
     */
    init (type = 0, msg = "", createTime) {
        this.node.getComponent(cc.Sprite).spriteFrame = this.itemSprite[type]
        let time = DWTool.timeParse(createTime / 1000)
        this.infoText.string = msg
        this.statusText.string = time
    },

    onLoad () {

    },

    start () {

    }
});
